openapi: 3.0.1
info:
  title: MockNodo
  description: Handling the configuration for mock Soap and Rest responses
  version: '1.0'
servers:
  - url: https://mil-d-apim.azure-api.net/mockNodo
paths:
  /:
    post:
      summary: mockSoap
      description: mockSoap
      operationId: mockSoap
      parameters:
        - name: Content-Type
          in: header
          required: true
          schema:
            enum:
              - application/xml
              - text/xml
            type: String
        - name: SOAPAction
          in: header
          required: true
          schema:
            enum:
              - verifyPaymentNotice
              - activatePaymentNoticeV2
            type: String
        - name: Cache-Control
          in: header
          schema:
            enum:
              - no-cache
            type: String
        - name: Headers
          in: header
          schema:
            enum:
              - '{SOAPAction="verifyPaymentNotice", Ocp-Apim-Subscription-Key=eeb0fe2b89df4d02ac4b0fe950319610, Accept=*/*}'
            type: String
      responses:
        '200':
          description: ''
  /closepayment:
    post:
      summary: mockRest
      description: mockRest
      operationId: mockRest
      responses:
        '200':
          description: ''
  /fees:
    post:
      summary: mockGec
      operationId: mockgec
      responses:
        '200':
          description: 
components: { }