#!/bin/sh
set -x
export resourceGroup="mil-d-weu-rg"
export vnetName="mil-d-weu-vnet"
export agwSubnetName="mil-d-weu-agw-snet"
export apimSubnetName="mil-d-weu-apim-snet"
export caeSubnetName="mil-d-weu-cae-snet"
export cosmosSubnetName="mil-d-weu-cosmos-snet"
export vnetAddressPrefix="10.0.0.0/16"
export agwSubnetAddressPrefix="10.0.1.0/24"
export apimSubnetAddressPrefix="10.0.2.0/24"
export caeSubnetAddressPrefix="10.0.4.0/23"
export cosmosSubnetAddressPrefix="10.0.3.0/24"
export agwName="mil-d-weu-agw"
export apimName="mil-d-weu-apim"
export logAnalyticsWorkspaceName="mil-d-weu-log"
export caeName="mil-d-weu-cae"
export cosmosName="mil-d-weu-cosmos"